# Generated by Django 5.2.7 on 2025-12-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_remove_product_collection_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('dresses', 'Dresses'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('outerwear', 'Outerwear'), ('accessories', 'Accessories')], default='dresses', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
