# Generated by Django 5.2.7 on 2025-12-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dress_type',
            field=models.CharField(blank=True, choices=[('', 'Not Applicable'), ('kente', 'Kente Dress'), ('ankara', 'Ankara Dress'), ('kaba_slit', 'Kaba & Slit'), ('african_print', 'African Print Dress'), ('dashiki', 'Dashiki Dress'), ('maxi', 'Maxi Dress'), ('midi', 'Midi Dress'), ('mini', 'Mini Dress'), ('bodycon', 'Bodycon Dress'), ('a_line', 'A-Line Dress'), ('wrap', 'Wrap Dress'), ('shift', 'Shift Dress'), ('peplum', 'Peplum Dress'), ('mermaid', 'Mermaid Dress'), ('ball_gown', 'Ball Gown'), ('evening_gown', 'Evening Gown'), ('cocktail', 'Cocktail Dress'), ('wedding', 'Wedding Dress'), ('bridesmaid', 'Bridesmaid Dress'), ('casual', 'Casual Dress'), ('office', 'Office Dress'), ('custom', 'Custom Design')], default='', max_length=50),
        ),
    ]
