# Generated by Django 5.2.7 on 2025-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_product_image_url_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('founder_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('studio_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('studio_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
